import Link from 'next/link';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { ArrowRight, Bot, Code, MousePointerClick, LayoutTemplate, Palette } from 'lucide-react';
import { Icons } from '@/components/icons';
import { placeholderImages } from '@/lib/placeholder-images';

function SiteHeader() {
  return (
    <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container flex h-14 max-w-screen-2xl items-center">
        <div className="mr-4 flex items-center">
          <Link href="/" className="mr-6 flex items-center space-x-2">
            <Icons.logo className="h-6 w-6" />
            <span className="font-bold sm:inline-block">
              CanvasCraft
            </span>
          </Link>
        </div>
        <div className="flex flex-1 items-center justify-end space-x-4">
          <Button variant="ghost" asChild>
             <Link href="/editor">
              Go to Editor <ArrowRight className="ml-2 h-4 w-4" />
            </Link>
          </Button>
        </div>
      </div>
    </header>
  );
}

function SiteFooter() {
  return (
    <footer className="py-6 md:px-8 md:py-0">
      <div className="container flex flex-col items-center justify-between gap-4 md:h-24 md:flex-row">
        <p className="text-balance text-center text-sm leading-loose text-muted-foreground md:text-left">
          Built by Firebase Studio.
        </p>
      </div>
    </footer>
  );
}

const features = [
  {
    icon: <MousePointerClick className="h-8 w-8" />,
    title: 'Drag & Drop Editor',
    description: 'Visually build your website with a simple and intuitive drag-and-drop interface.',
  },
  {
    icon: <Palette className="h-8 w-8" />,
    title: 'Style Panel',
    description: 'Customize every element with a powerful style panel for colors, fonts, spacing, and more.',
  },
  {
    icon: <LayoutTemplate className="h-8 w-8" />,
    title: 'Responsive Design',
    description: 'Preview and design your site for desktop, tablet, and mobile devices effortlessly.',
  },
  {
    icon: <Code className="h-8 w-8" />,
    title: 'Real-time Code Export',
    description: 'Instantly generate and export clean, production-ready HTML and CSS for your project.',
  },
   {
    icon: <Bot className="h-8 w-8" />,
    title: 'AI Template Generation',
    description: 'Kickstart your project with a custom template generated by AI based on your description.',
  },
];

export default function Home() {
  const heroImage = placeholderImages.find(p => p.id === 'hero-dashboard');

  return (
    <div className="flex min-h-screen flex-col">
      <SiteHeader />
      <main className="flex-1">
        <section className="relative py-24 md:py-32 lg:py-40">
           <div className="absolute top-0 -z-10 h-full w-full bg-background"><div className="absolute bottom-auto left-auto right-0 top-0 h-[500px] w-[500px] -translate-x-[30%] translate-y-[20%] rounded-full bg-[rgba(59,130,246,0.5)] opacity-50 blur-[80px]"></div></div>

          <div className="container relative flex max-w-screen-lg flex-col items-center gap-6 text-center">
            <h1 className="font-sans text-5xl font-bold tracking-tighter sm:text-6xl md:text-7xl">
              Build modern websites, visually.
            </h1>
            <p className="max-w-2xl leading-normal text-muted-foreground sm:text-xl sm:leading-8">
              CanvasCraft is a no-code website builder that helps you design and launch your ideas faster. Drag, drop, and customize. We'll handle the code.
            </p>
            <div className="mt-6">
              <Button asChild size="lg" className="font-semibold text-lg px-6 py-6 rounded-lg transition-transform hover:scale-105">
                <Link href="/editor">
                  Start Building for Free <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
            </div>
          </div>
          {heroImage && (
            <div className="container max-w-screen-xl mx-auto mt-16 lg:mt-24">
              <div className="relative rounded-xl border bg-secondary/50 shadow-2xl shadow-primary/10">
                 <Image
                  src={heroImage.imageUrl}
                  alt={heroImage.description}
                  width={1200}
                  height={750}
                  className="rounded-t-lg"
                  data-ai-hint={heroImage.imageHint}
                  priority
                />
                 <div className="rounded-b-lg border-t p-2 bg-background/50">
                    <div className="flex items-center gap-1.5">
                        <div className="h-3 w-3 rounded-full bg-red-500"></div>
                        <div className="h-3 w-3 rounded-full bg-yellow-500"></div>
                        <div className="h-3 w-3 rounded-full bg-green-500"></div>
                    </div>
                </div>
              </div>
            </div>
          )}
        </section>
        <section id="features" className="container space-y-12 py-8 md:py-12 lg:py-24">
          <div className="mx-auto flex max-w-3xl flex-col items-center space-y-4 text-center">
            <h2 className="text-4xl font-bold tracking-tighter md:text-5xl">Features</h2>
            <p className="max-w-2xl leading-normal text-muted-foreground sm:text-lg sm:leading-7">
              Everything you need to turn your idea into a stunning website, and nothing you don't.
            </p>
          </div>
          <div className="mx-auto grid justify-center gap-8 sm:grid-cols-2 md:max-w-4xl md:grid-cols-3">
            {features.map((feature) => (
              <div key={feature.title} className="flex flex-col items-center text-center gap-4">
                 <div className="flex h-16 w-16 items-center justify-center rounded-full bg-secondary text-primary">
                    {feature.icon}
                  </div>
                <div className="space-y-2">
                  <h3 className="font-bold text-xl">{feature.title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">{feature.description}</p>
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>
      <SiteFooter />
    </div>
  );
}
