import Link from 'next/link';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { ArrowRight, Bot, Code, MousePointerClick, LayoutTemplate, Palette } from 'lucide-react';
import { Icons } from '@/components/icons';
import { placeholderImages } from '@/lib/placeholder-images';

function SiteHeader() {
  return (
    <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container flex h-14 max-w-screen-2xl items-center">
        <div className="mr-4 hidden md:flex">
          <Link href="/" className="mr-6 flex items-center space-x-2">
            <Icons.logo className="h-6 w-6" />
            <span className="hidden font-bold sm:inline-block">
              CanvasCraft
            </span>
          </Link>
        </div>
        <div className="flex flex-1 items-center justify-end space-x-2">
          <Button asChild>
            <Link href="/editor">
              Go to Editor <ArrowRight className="ml-2 h-4 w-4" />
            </Link>
          </Button>
        </div>
      </div>
    </header>
  );
}

function SiteFooter() {
  return (
    <footer className="py-6 md:px-8 md:py-0">
      <div className="container flex flex-col items-center justify-between gap-4 md:h-24 md:flex-row">
        <p className="text-balance text-center text-sm leading-loose text-muted-foreground md:text-left">
          Built by Firebase Studio.
        </p>
      </div>
    </footer>
  );
}

const features = [
  {
    icon: <MousePointerClick className="h-10 w-10 text-primary" />,
    title: 'Drag & Drop Editor',
    description: 'Visually build your website with a simple and intuitive drag-and-drop interface.',
  },
  {
    icon: <Palette className="h-10 w-10 text-primary" />,
    title: 'Style Panel',
    description: 'Customize every element with a powerful style panel for colors, fonts, spacing, and more.',
  },
  {
    icon: <LayoutTemplate className="h-10 w-10 text-primary" />,
    title: 'Responsive Design',
    description: 'Preview and design your site for desktop, tablet, and mobile devices effortlessly.',
  },
  {
    icon: <Code className="h-10 w-10 text-primary" />,
    title: 'Real-time Code Export',
    description: 'Instantly generate and export clean, production-ready HTML and CSS for your project.',
  },
   {
    icon: <Bot className="h-10 w-10 text-primary" />,
    title: 'AI Template Generation',
    description: 'Kickstart your project with a custom template generated by AI based on your description.',
  },
];

export default function Home() {
  const heroImage = placeholderImages.find(p => p.id === 'hero-dashboard');

  return (
    <div className="flex min-h-screen flex-col">
      <SiteHeader />
      <main className="flex-1">
        <section className="space-y-6 pb-8 pt-6 md:pb-12 md:pt-10 lg:py-32">
          <div className="container flex max-w-[64rem] flex-col items-center gap-4 text-center">
            <h1 className="font-headline text-4xl font-extrabold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">
              Build websites visually. No code required.
            </h1>
            <p className="max-w-[42rem] leading-normal text-muted-foreground sm:text-xl sm:leading-8">
              CanvasCraft is a no-code website builder that helps you design and launch your ideas faster. Drag, drop, and customize. We'll handle the code.
            </p>
            <div className="space-x-4">
              <Button asChild size="lg">
                <Link href="/editor">
                  Start Building for Free
                </Link>
              </Button>
            </div>
          </div>
          {heroImage && (
            <div className="container max-w-screen-xl mx-auto mt-12 lg:mt-20">
              <div className="relative rounded-xl border bg-card shadow-xl">
                 <Image
                  src={heroImage.imageUrl}
                  alt={heroImage.description}
                  width={1200}
                  height={750}
                  className="rounded-t-xl"
                  data-ai-hint={heroImage.imageHint}
                  priority
                />
                 <div className="rounded-b-xl border-t p-2 bg-card/50">
                    <div className="flex items-center gap-1.5">
                        <div className="h-3 w-3 rounded-full bg-red-500"></div>
                        <div className="h-3 w-3 rounded-full bg-yellow-500"></div>
                        <div className="h-3 w-3 rounded-full bg-green-500"></div>
                    </div>
                </div>
              </div>
            </div>
          )}
        </section>
        <section id="features" className="container space-y-6 bg-slate-50 dark:bg-transparent py-8 md:py-12 lg:py-24 rounded-xl">
          <div className="mx-auto flex max-w-[58rem] flex-col items-center space-y-4 text-center">
            <h2 className="font-headline text-3xl leading-[1.1] sm:text-3xl md:text-5xl font-bold">Features</h2>
            <p className="max-w-[85%] leading-normal text-muted-foreground sm:text-lg sm:leading-7">
              Everything you need to turn your idea into a stunning website.
            </p>
          </div>
          <div className="mx-auto grid justify-center gap-4 sm:grid-cols-2 md:max-w-[64rem] md:grid-cols-3">
            {features.map((feature) => (
              <div key={feature.title} className="relative overflow-hidden rounded-lg border bg-background p-2">
                <div className="flex h-[180px] flex-col justify-between rounded-md p-6">
                  {feature.icon}
                  <div className="space-y-2">
                    <h3 className="font-bold">{feature.title}</h3>
                    <p className="text-sm text-muted-foreground">{feature.description}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>
      <SiteFooter />
    </div>
  );
}
